Repository e-sau/step-by-step, pull requests merged in 2020-12, with the labels that each got.

#56 Add eslint
  .eslintrc.json
  resources/js/src/components/LoginForm.js
  resources/js/src/components/Summary/Summary.js
  resources/js/src/components/indexPage/blockPreview/styled.sc.js
  resources/js/src/components/signupPage/SignupFormWrapper.js
  resources/js/src/components/signupPage/index.js
  resources/js/src/components/tasksPage/index.js
  resources/js/src/components/ui/Popup.js
  resources/js/src/containers/HeaderContainer.js
  resources/js/src/containers/PopupContainer.js
  resources/js/src/layout/Header.js
  resources/js/src/layout/index.js
  resources/js/src/store/auth/actions.js
  resources/js/src/store/auth/reducer.js
  resources/js/src/store/auth/types.js
Labels: enhancement

#61 Feature/IS100-52/add-messages-view
  package.json
  resources/js/src/common/helpers.js
  resources/js/src/common/validators.js
  resources/js/src/components/MessagePreview/index.js
  resources/js/src/components/MessagePreview/styled.sc.js
  resources/js/src/components/accountPage/index.js
  resources/js/src/components/accountPage/messagesBlock/index.js
  resources/js/src/components/accountPage/messagesBlock/styled.sc.js
  resources/js/src/components/accountPage/styled.cs.js
  resources/js/src/containers/AccountPageContainer.js
  resources/js/src/containers/MessagesContainer.js
Labels: frontend

#68 feature/IS100-40/add-user-rating
  package.json
  resources/js/src/api/endpoints/ratings.js
  resources/js/src/api/makeRequest.js
  resources/js/src/components/accountPage/profileCard/index.js
  resources/js/src/components/accountPage/profileCard/styled.sc.js
  resources/js/src/components/accountPage/profileEditForm/index.js
  resources/js/src/components/accountPage/sidePanel/index.js
  resources/js/src/components/accountPage/sidePanel/styled.sc.js
  resources/js/src/components/ratingStars/index.js
  resources/js/src/components/ratingStars/styled.sc.js
  resources/js/src/components/ui/Spacer.js
  resources/js/src/layout/Header.js
  resources/js/src/models/User.js
  resources/js/src/store/auth/workers.js
  resources/js/src/store/grade/workers.js
  resources/js/src/store/subject/workers.js
  resources/js/src/store/user/actions.js
  resources/js/src/store/user/reducer.js
  resources/js/src/store/user/types.js
  resources/js/src/store/user/watchers.js
  resources/js/src/store/user/workers.js
Labels: frontend

#69 feature/IS100-18/update-index-page
  public/images/tasks/example/example-1.png
  public/images/tasks/example/example-2.png
  resources/js/src/api/endpoints/__example__.js
  resources/js/src/api/endpoints/auth.js
  resources/js/src/api/endpoints/reviews.js
  resources/js/src/api/endpoints/user.js
  resources/js/src/common/helpers.js
  resources/js/src/components/Card/Card.js
  resources/js/src/components/Card/styled.sc.js
  resources/js/src/components/LoginForm.js
  resources/js/src/components/accountPage/index.js
  resources/js/src/components/accountPage/sidePanel/index.js
  resources/js/src/components/indexPage/BlockReviews.js
  resources/js/src/components/indexPage/blockExample/index.js
  resources/js/src/components/indexPage/index.js
  resources/js/src/components/taskExample/index.js
  resources/js/src/components/taskExample/styled.sc.js
  resources/js/src/containers/AccountPageContainer.js
  resources/js/src/containers/IndexPageContainer.js
  resources/js/src/containers/SiteContainer.js
  resources/js/src/models/Model.js
  resources/js/src/models/Review.js
  resources/js/src/models/Task.js
  resources/js/src/models/User.js
  resources/js/src/routes.js
  resources/js/src/store/auth/watchers.js
  resources/js/src/store/auth/workers.js
  resources/js/src/store/review/actions.js
  resources/js/src/store/review/reducer.js
  resources/js/src/store/review/types.js
  resources/js/src/store/review/watchers.js
  resources/js/src/store/review/workers.js
  resources/js/src/store/rootReducer.js
  resources/js/src/store/rootSaga.js
  resources/js/src/store/site/actions.js
  resources/js/src/store/site/reducer.js
  resources/js/src/store/site/types.js
  resources/js/src/store/site/watchers.js
  resources/js/src/store/site/workers.js
  resources/js/test/api/endpoints/__example__.test.js
  resources/js/test/api/endpoints/auth.test.js
  resources/js/test/api/endpoints/grades.test.js
  resources/js/test/api/endpoints/reviews.test.js
  resources/js/test/api/endpoints/subjects.test.js
  resources/js/test/api/endpoints/tasks.test.js
  resources/js/test/api/endpoints/user.test.js
  resources/js/test/api/makeRequest.test.js
Labels: frontend

#72 Feature/is100 30/task page
  public/images/icream-on-stick.png
  public/images/tasks/book.png
  public/images/tasks/icecream.png
  public/images/tasks/rope.png
  resources/js/src/api/endpoints/subjects.js
  resources/js/src/api/endpoints/tasks.js
  resources/js/src/common/helpers.js
  resources/js/src/components/ExampleTasks/examples.js
  resources/js/src/components/ExampleTasks/index.js
  resources/js/src/components/Preview/index.js
  resources/js/src/components/SubjectSelect/index.js
  resources/js/src/components/Task/icream-on-stick.png
  resources/js/src/components/Task/index.js
  resources/js/src/components/Task/styled.sc.js
  resources/js/src/components/TaskPreview/index.js
  resources/js/src/components/TaskPreview/styled.sc.js
  resources/js/src/components/ui/GoBackLink/index.js
  resources/js/src/components/ui/GoBackLink/styled.sc.js
  resources/js/src/containers/SubjectsPageContainer.js
  resources/js/src/models/Review.js
  resources/js/src/models/Subject.js
  resources/js/src/models/Task.js
  resources/js/src/models/User.js
  resources/js/src/pages/AccountPage.js
  resources/js/src/pages/SignupPage.js
  resources/js/src/pages/SubjectsPage.js
  resources/js/src/pages/styles/accountPageStyles.sc.js
  resources/js/src/pages/styles/signupPageStyles.sc.js
  resources/js/src/pages/styles/subjectsPageStyles.sc.js
  resources/js/src/routes.js
  resources/js/src/store/rootSaga.js
  resources/js/src/store/subject/actions.js
  resources/js/src/store/subject/reducer.js
  resources/js/src/store/subject/types.js
  resources/js/src/store/subject/watchers.js
  resources/js/src/store/subject/workers.js
  resources/js/src/store/task/actions.js
  resources/js/src/store/task/reducer.js
  resources/js/src/store/task/selectors.js
  resources/js/src/store/task/types.js
  resources/js/src/store/task/watchers.js
  resources/js/src/store/task/workers.js
  resources/js/test/api/endpoints/tasks.test.js
  resources/js/test/common/helpers.test.js
Labels: frontend

#74 feature/is100-68/add-fetch-subjects
  app/Services/UserService.php
  resources/js/src/api/endpoints/subjects.js
  resources/js/src/api/endpoints/user.js
  resources/js/src/components/AvailableSubjectPreview/index.js
  resources/js/src/components/AvailableSubjectPreview/styled.sc.js
  resources/js/src/components/CompletedSubjectPreview/index.js
  resources/js/src/components/CompletedSubjectPreview/styled.sc.js
  resources/js/src/components/CompletedTasks/index.js
  resources/js/src/components/SubjectsList/index.js
  resources/js/src/components/SubjectsList/styled.sc.js
  resources/js/src/containers/AccountPageContainer.js
  resources/js/src/containers/SubjectsAvailableContainer.js
  resources/js/src/containers/SubjectsCompleteContainer.js
  resources/js/src/models/Subject.js
  resources/js/src/store/subject/selectors.js
  resources/js/src/store/subject/workers.js
  resources/js/test/api/endpoints/subjects.test.js
Labels: frontend

#80 feature/IS100-67/add-task-photos
  app/Http/Resources/Task.php
  app/Models/Task.php
  composer.json
  database/migrations/2020_12_21_140953_alter_table_tasks_add_image_column.php
  database/seeders/TasksTableSeeder.php
  resources/js/src/components/Task/index.js
  resources/js/src/components/Task/styled.sc.js
  resources/js/src/models/Task.js
Labels: backend, frontend

#81 feature/is100-70/save-user-profile
  .github/workflows/node.yaml
  app/Http/Controllers/Api/UserController.php
  package.json
  resources/js/src/components/ProfileEditForm/index.js
  resources/js/src/components/ProfileEditForm/styled.sc.js
  resources/js/src/components/signupPage/SignupFormWrapper.js
  resources/js/src/components/signupPage/index.js
  resources/js/src/components/signupPage/styled.sc.js
  resources/js/src/containers/ProfileEditFormContainer.js
  resources/js/src/models/User.js
  resources/js/src/pages/SignupPage.js
  resources/js/src/store/user/actions.js
  resources/js/src/store/user/reducer.js
  resources/js/src/store/user/workers.js
Labels: backend, frontend

#83 Is100 72
  app/Http/Controllers/Api/UserController.php
  app/Http/Controllers/Api/UserTaskController.php
  app/Models/Task.php
  app/Models/User.php
  app/Models/UserTask.php
  app/Services/UserService.php
  routes/api.php
Labels: backend

#84 feature/is100-73/add-ability-to-resolve-tasks
  app/Http/Controllers/Api/UserTaskController.php
  app/Models/Task.php
  app/Models/UserTask.php
  app/Services/UserService.php
  database/seeders/TasksTableSeeder.php
  resources/js/src/api/endpoints/user.js
  resources/js/src/models/Task.js
  resources/js/src/store/auth/selectors.js
  resources/js/src/store/subject/workers.js
  resources/js/src/store/task/actions.js
  resources/js/src/store/task/workers.js
Labels: backend, frontend

#85 update main branch
  .github/workflows/node.yaml
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Controllers/Api/UserTaskController.php
  app/Http/Resources/Task.php
  app/Models/Task.php
  app/Models/User.php
  app/Models/UserTask.php
  app/Services/UserService.php
  composer.json
  database/migrations/2020_12_21_140953_alter_table_tasks_add_image_column.php
  database/seeders/TasksTableSeeder.php
  package.json
  resources/js/src/api/endpoints/user.js
  resources/js/src/components/ProfileEditForm/index.js
  resources/js/src/components/ProfileEditForm/styled.sc.js
  resources/js/src/components/SignupFormWrapper.js
  resources/js/src/components/Task/index.js
  resources/js/src/components/Task/styled.sc.js
  resources/js/src/components/signupPage/SignupFormWrapper.js
  resources/js/src/components/signupPage/index.js
  resources/js/src/components/signupPage/styled.sc.js
  resources/js/src/containers/ProfileEditFormContainer.js
  resources/js/src/models/Model.js
  resources/js/src/models/Task.js
  resources/js/src/models/User.js
  resources/js/src/pages/SignupPage.js
  resources/js/src/store/auth/selectors.js
  resources/js/src/store/subject/workers.js
  resources/js/src/store/task/actions.js
  resources/js/src/store/task/workers.js
  resources/js/src/store/user/actions.js
  resources/js/src/store/user/reducer.js
  resources/js/src/store/user/workers.js
  routes/api.php
Labels: enhancement
