Repository e-sau/step-by-step, pull requests merged in 2020-11, with the labels that each got.

#11 Add signup and login pages
  .babelrc
  package.json
  resources/css/app.css
  resources/js/src/common/api/UserAPI.js
  resources/js/src/common/api/makeRequest.js
  resources/js/src/common/helpers/objectHelpers.js
  resources/js/src/common/regexp/index.js
  resources/js/src/common/validators/index.js
  resources/js/src/components/loginPage/index.js
  resources/js/src/components/loginPage/styled.sc.js
  resources/js/src/components/pageNotFound/PageNotFound.js
  resources/js/src/components/signupPage/form/index.js
  resources/js/src/components/signupPage/index.js
  resources/js/src/components/signupPage/styled.sc.js
  resources/js/src/containers/LoginPageContainer.js
  resources/js/src/containers/SignupPageContainer.js
  resources/js/src/domains/__example__/selectors.js
  resources/js/src/domains/__example__/watchers.js
  resources/js/src/domains/__example__/workers.js
  resources/js/src/domains/auth/actions.js
  resources/js/src/domains/auth/reducer.js
  resources/js/src/domains/auth/selectors.js
  resources/js/src/domains/auth/types.js
  resources/js/src/domains/auth/watchers.js
  resources/js/src/domains/auth/workers.js
  resources/js/src/dto/DTO.js
  resources/js/src/dto/User.js
  resources/js/src/rootReducer.js
  resources/js/src/rootSaga.js
  resources/js/src/routes.js
  resources/js/src/store.js
Labels: frontend

#15 Create CODEOWNERS
  .github/CODEOWNERS
Labels: DX

#14 Add Breadcrumbs
  resources/js/src/components/Breadcrumbs.js
Labels: frontend

#12 Auth fixes
  app/Models/User.php
  resources/js/src/common/api/UserAPI.js
  resources/js/src/common/api/makeRequest.js
  resources/js/src/common/validators/index.js
  resources/js/src/components/form/index.js
  resources/js/src/components/form/styled.sc.js
  resources/js/src/components/loginPage/index.js
  resources/js/src/components/signupPage/form/index.js
  resources/js/src/components/signupPage/index.js
  resources/js/src/components/signupPage/styled.sc.js
  resources/js/src/containers/LoginPageContainer.js
  resources/js/src/containers/SignupPageContainer.js
  resources/js/src/domains/auth/reducer.js
  resources/js/src/domains/auth/types.js
  resources/js/src/domains/auth/workers.js
  resources/js/src/dto/DTO.js
  resources/js/src/dto/User.js
Labels: frontend

#22 IS100-5
  .env.example
  resources/js/src/app.js
  resources/js/src/common/api/endpoints/grades.js
  resources/js/src/common/api/endpoints/subjects.js
  resources/js/src/common/api/endpoints/tasks.js
  resources/js/src/common/api/endpoints/users.js
  resources/js/src/common/api/makeRequest.js
  resources/js/src/common/helpers/object.js
  resources/js/src/common/helpers/string.js
  resources/js/src/containers/LoginPageContainer.js
  resources/js/src/containers/SignupPageContainer.js
  resources/js/src/containers/SiteContainer.js
  resources/js/src/domains/auth/actions.js
  resources/js/src/domains/auth/reducer.js
  resources/js/src/domains/auth/selectors.js
  resources/js/src/domains/auth/types.js
  resources/js/src/domains/auth/watchers.js
  resources/js/src/domains/auth/workers.js
  resources/js/test/common/api/endpoints/users.test.js
Labels: frontend

#31 Add Spacer component
  resources/js/src/components/Spacer.js
Labels: DX, frontend

#45 Add node.yaml
  .github/workflows/node.yaml
Labels: DX

#48 [IS100-45&44] Fix styles
  resources/js/src/components/LoginForm.js
  resources/js/src/components/indexPage/blockFeatures/index.js
  resources/js/src/components/indexPage/blockPreview/styled.sc.js
  resources/js/src/components/indexPage/blockSubjects/styled.sc.js
  resources/js/src/components/indexPage/index.js
  resources/js/src/components/indexPage/styled.sc.js
  resources/js/src/components/taskExample/styled.sc.js
  resources/js/src/components/ui/HorizontalScroll.js
  resources/js/src/layout/styled.sc.js
Labels: bug, frontend, styles

#47 Feature/is100-39/add profile card
  package.json
  public/images/no-avatar.png
  resources/js/src/common/helpers.js
  resources/js/src/common/memo.js
  resources/js/src/components/accountPage/sidePanel/index.js
  resources/js/src/components/profileCard/index.js
  resources/js/src/components/profileCard/styled.sc.js
  resources/js/src/containers/AccountPageContainer.js
  resources/js/src/containers/HeaderContainer.js
  resources/js/src/containers/LoginFormContainer.js
  resources/js/src/containers/SignupPageContainer.js
  resources/js/src/models/User.js
  resources/js/src/store/auth/actions.js
  resources/js/src/store/auth/reducer.js
  resources/js/src/store/auth/selectors.js
  resources/js/src/store/auth/types.js
  resources/js/src/store/auth/workers.js
  resources/js/src/store/rootReducer.js
  resources/js/src/store/rootSaga.js
  resources/js/src/store/user/actions.js
  resources/js/src/store/user/reducer.js
  resources/js/src/store/user/selectors.js
  resources/js/src/store/user/types.js
  resources/js/test/common/helpers.test.js
Labels: frontend
